version: '2'
services:

  mysql:
     container_name: mysql
     image: mysql
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD:
     volumes:
      - ~/mysql:/var/lib/mysql

  alpinephp:
    container_name: alpinephp
    image: superviz/218
    links:
      - mysql:mysql
    environment:
      TZ: America/Sao_Paulo
      MONGO_DB_HOST: mysql
      MONGO_DB_PORT: 3306
      MONGO_DB_DATABASE: database
      MONGO_DB_USERNAME:
      MONGO_DB_PASSWORD:
    volumes:
     -  ../SuperViz-Web:/var/www/src
    ports:
      - "8180:80"

volumes:
  redis:
  yarn:
  data:
    driver: "local"