version: '2'
services:

  mysql:
     container_name: mysql
     image: mysql
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: root
     volumes:
      - ~/mysql:/var/lib/mysql
     ports:
       - "3306:3306"

  alpinephp:
    container_name: api
    image: josebispo/superviz-218
    links:
      - mysql:mysql
    environment:
      TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
    ports:
      - "8180:80"

  web:
    container_name: VueJS
    image: josebispo/superviz-218
    environment:
        TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
     -  ./vue-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     -  ./vue-conf/nginx/default:/etc/nginx/sites-enabled/default
    ports:
     - "777:8080"

volumes:
  redis:
  yarn:
  data:
    driver: "local"

