version: '3'
services:

  mysql:
     container_name: mysql
     image: mysql
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: root
     volumes:
      - ~/mysql:/var/lib/mysql
     ports:
       - "3306:3306"

######################################
# API Container
######################################
  api:
    container_name: superviz-api
    image: josebispo/superviz-218
    links:
      - mysql:mysql
    environment:
      TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
     -  ./config/nginx/api:/etc/nginx/sites-enabled/default
     -  ./config/nginx/keys/superviz_com.crt:/etc/ssl/certs/superviz_com.crt
     -  ./config/nginx/keys/superviz_com.key:/etc/ssl/private/superviz_com.key
    restart: unless-stopped
    ports:
     - "80" #sites

######################################
# Mobile Containers
######################################
  mobile:
    container_name: superviz-mobile
    image: josebispo/superviz-218
    environment:
        TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
     -  ./vue-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     -  ./vue-conf/nginx/default:/etc/nginx/sites-enabled/default
    restart: unless-stopped
    ports:
     - "80:80" #mobile

######################################
# NGINX
######################################
  nginx:
     container_name: superviz-nginx
     volumes:
      -  ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
     build:
       context: ./config/nginx/
       dockerfile: ./Dockerfile
     restart: unless-stopped
     ports:
       - 69:80
