version: '2'
services:

  mysql:
     container_name: mysql
     image: mysql
     environment:
       TZ: America/Sao_Paulo
       MYSQL_USER: root
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: superviz
     volumes:
      - ~/mysql:/var/lib/mysql

  alpinephp:
    container_name: alpinephp
    image: superviz/218
    links:
      - mysql:mysql
    environment:
      TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
    ports:
      - "8180:80"

volumes:
  redis:
  yarn:
  data:
    driver: "local"