version: '2'
services:

  mysql:
     container_name: mysql_homelist
     image: mysql
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: root
     volumes:
      - ~/mysql:/var/lib/mysql
     ports:
       - "3309:3306"

  alpinephp:
    container_name: homelist_api
    image: josebispo/superviz-218
    links:
      - mysql:mysql
    environment:
      TZ: America/Sao_Paulo
    volumes:
     -  ../homelist-laravel:/var/www/src
     -  ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
     -  ./config/nginx/default:/etc/nginx/sites-enabled/default
    ports:
      - "8181:80"
      - "1990:1990"

  web:
    container_name: VueJS
    image: josebispo/superviz-218
    environment:
        TZ: America/Sao_Paulo
    volumes:
     -  /Users/bispo/projects/homelist-laravel:/var/www/src
     -  ./vue-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     -  ./vue-conf/nginx/default:/etc/nginx/sites-enabled/default
    ports:
     - "777:8080"

volumes:
  redis:
  yarn:
  data:
    driver: "local"

