version: '2'
services:

  mysql:
     container_name: mysql
     image: mysql
     environment:
       TZ: America/Sao_Paulo
       MYSQL_ROOT_PASSWORD: root
     volumes:
      - ~/mysql:/var/lib/mysql
     ports:
       - "3306:3306"

  alpinephp:
    container_name: Api
    image: josebispo/superviz-218
    links:
      - mysql:mysql
    environment:
      TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
     -  ./config/nginx/default:/etc/nginx/sites-enabled/default
     -  ./config/nginx/superviz_com.crt:/etc/ssl/certs/superviz_com.crt
     -  ./config/nginx/superviz_com.key:/etc/ssl/private/superviz_com.key
    ports:
     - "80:443" #sites
     - "1990:1990" #swagger

  web:
    container_name: Mobile
    image: josebispo/superviz-218
    environment:
        TZ: America/Sao_Paulo
    volumes:
     -  ../SuperViz-Web:/var/www/src
     -  ./vue-conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     -  ./vue-conf/nginx/default:/etc/nginx/sites-enabled/default
    ports:
     - "777:8080" #mobile

volumes:
  redis:
  yarn:
  data:
    driver: "local"

